# Generated by Django 5.1.7 on 2025-03-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.TextField(default='No description', max_length=500)),
                ('count', models.IntegerField()),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
